language: python
python:
  - 2.7

sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt
  - docker pull dgarros/tcpreplay
  - docker build -t fluent-plugin-juniper-telemetry .

script:
  - python -m pytest -v --durations=5
  - docker logs fluent-plugin-juniper-telemetry_test
  - docker logs tcpreplay_test
